# https://docs.docker.com/compose/compose-file/compose-file-v3/ - prefer long syntax, it is easier to understand
version: '3.8'
services:
  keycloak:
    image: bitnami/keycloak
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER= true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/realm-export.json  # Path to import realm configuration
      - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/realm-export.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING -Dkeycloak.migration.realmName=demo
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=mysecretpassword
    ports:
      - "8080:8080"
    volumes:
      - ./realm-export.json:/realm-export.json  # Mount realm-export.json into the container
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host

